Repository lkorasik/ToDoBot, pull requests merged in 2020-11, with the labels that each got.

#42 Add Keyboard
  src/main/java/com/core/Constants.java
  src/main/java/com/core/RequestHandler.java
  src/main/java/com/telegrambot/Bot.java
Labels: enhancement

#43 Implement saving users data
  pom.xml
  src/main/java/com/core/Constants.java
  src/main/java/com/core/Core.java
  src/test/java/com/core/CoreTest.java
Labels: enhancement

#44 Test
  .gitignore
  src/main/java/com/core/Core.java
  src/test/java/com/core/CoreTest.java
Labels: enhancement

#45 Implement todo and completed tasks
  src/main/java/com/authentication/Authenticator.java
  src/main/java/com/core/Constants.java
  src/main/java/com/core/Core.java
  src/main/java/com/core/RequestHandler.java
  src/main/java/com/core/User.java
  src/main/java/com/fsm/FSM.java
  src/main/java/com/fsm/State.java
Labels: bug, enhancement

#47 Add buttons in telegram
  src/main/java/com/core/Constants.java
  src/main/java/com/telegrambot/Bot.java
Labels: enhancement

#49 Separate fsm states
  src/main/java/com/authentication/Authenticator.java
  src/main/java/com/consolebot/ConsoleBot.java
  src/main/java/com/core/Constants.java
  src/main/java/com/core/Core.java
  src/main/java/com/core/RequestHandler.java
  src/main/java/com/core/User.java
  src/main/java/com/fsm/FSM.java
Labels: bug

#50 Add notification
  src/main/java/com/consolebot/ConsoleBot.java
  src/main/java/com/core/Constants.java
  src/main/java/com/core/Core.java
  src/main/java/com/core/DateConverter.java
  src/main/java/com/core/DateType.java
  src/main/java/com/core/NotExistingTaskIndexException.java
  src/main/java/com/core/RequestHandler.java
  src/main/java/com/core/Task.java
  src/main/java/com/core/User.java
  src/main/java/com/fsm/FSM.java
  src/main/java/com/fsm/State.java
  src/main/java/com/telegrambot/Bot.java
Labels: enhancement

#51 Add test for timer
  src/main/java/com/core/DateConverter.java
  src/main/java/com/core/DateType.java
  src/main/java/com/core/RequestHandler.java
  src/test/java/com/core/RequestHandlerTest.java
Labels: enhancement
