Repository lkorasik/ToDoBot, pull requests merged in 2020-10, with the labels that each got.

#1 Add telegram bot
  pom.xml
  src/main/java/com/telegrambot/Bot.java
  src/main/java/com/telegrambot/StartBot.java
Labels: enhancement

#2 Implement bot core and simple cli
  pom.xml
  src/main/java/com/consolebot/ConsoleBot.java
  src/main/java/com/core/Core.java
  src/main/java/com/core/Task.java
Labels: enhancement

#7 Add parser
  src/main/java/com/core/CommandSplitter.java
  src/main/java/com/core/ParsedCommand.java
Labels: enhancement

#17 Add tg integration
  src/main/java/com/telegrambot/Bot.java
Labels: enhancement

#18 Add commands constants
  src/main/java/com/core/CommandsNames.java
  src/main/java/com/telegrambot/Bot.java
Labels: enhancement, style

#19 Add test
  src/test/java/com/core/CommandSplitterTest.java
  src/test/java/com/todobot/AppTest.java
Labels: enhancement

#20 Add test
  src/main/java/com/telegrambot/Bot.java
  src/test/java/com/core/ParsedCommandsTest.java
Labels: enhancement

#21 Secure tokens
  .gitignore
  src/main/java/com/telegrambot/Bot.java
  src/main/java/com/telegrambot/TokenLoader.java
Labels: enhancement

#22 Add core tests
  src/main/java/com/consolebot/ConsoleBot.java
  src/main/java/com/core/Core.java
  src/main/java/com/core/Task.java
  src/test/java/com/core/CoreTest.java
  src/test/java/com/core/TaskTest.java
Labels: enhancement

#24 Enhance RequestHandler, make addTask and deleteTask void
  src/main/java/com/consolebot/ConsoleBot.java
  src/main/java/com/core/Core.java
  src/main/java/com/core/RequestHandler.java
  src/main/java/com/core/incorrectTaskIdException.java
  src/main/java/com/core/notExistingTaskIndexException.java
  src/test/java/com/core/CoreTest.java
Labels: enhancement

#25 Add more tests for Core and RequestHandler
  src/main/java/com/core/Core.java
  src/test/java/com/core/CoreTest.java
  src/test/java/com/core/RequestHandlerTest.java
Labels: enhancement

#27 Refactoring
  src/main/java/com/consolebot/ConsoleBot.java
  src/main/java/com/core/RequestHandler.java
  src/main/java/com/telegrambot/Bot.java
  src/test/java/com/core/RequestHandlerTest.java
Labels: enhancement

#28 Refactor exceptions and add more document comments
  src/main/java/com/consolebot/ConsoleBot.java
  src/main/java/com/core/Core.java
  src/main/java/com/core/IncorrectTaskIdTypeException.java
  src/main/java/com/core/NotExistingTaskIndexException.java
  src/main/java/com/core/RequestHandler.java
  src/main/java/com/core/Task.java
  src/main/java/com/core/incorrectTaskIdException.java
  src/main/java/com/core/notExistingTaskIndexException.java
  src/test/java/com/core/CoreTest.java
Labels: enhancement

#30 Add test
  src/main/java/com/telegrambot/Bot.java
  src/test/java/com/core/ParsedCommandsTest.java
  src/test/java/com/core/RequestHandlerTest.java
Labels: enhancement

#32 Add more tests
  src/test/java/com/core/RequestHandlerTest.java
Labels: enhancement

#33 Refactor test
  src/test/java/com/core/ParsedCommandsTest.java
  src/test/java/com/core/RequestHandlerTest.java
  src/test/java/com/core/TaskTest.java
Labels: style

#36 Merger
  src/main/java/com/authentication/Authenticator.java
  src/main/java/com/consolebot/ConsoleBot.java
  src/main/java/com/core/Constants.java
  src/main/java/com/core/Core.java
  src/main/java/com/core/RequestHandler.java
  src/main/java/com/fsm/FSM.java
  src/main/java/com/fsm/State.java
  src/main/java/com/fsm/Transition.java
  src/main/java/com/fsm/TransitionTable.java
  src/main/java/com/telegrambot/Bot.java
Labels: enhancement

#37 Authentication
  src/main/java/com/authentication/Authenticator.java
  src/main/java/com/consolebot/ConsoleBot.java
  src/main/java/com/core/Constants.java
  src/main/java/com/core/Core.java
  src/main/java/com/core/RequestHandler.java
Labels: enhancement

#38 Refactor
  src/main/java/com/core/Constants.java
  src/main/java/com/core/RequestHandler.java
  src/main/java/com/fsm/FSM.java
  src/main/java/com/fsm/TransitionTable.java
Labels: enhancement

#39 Fix
  src/main/java/com/core/Constants.java
  src/main/java/com/core/RequestHandler.java
Labels: enhancement

#40 Fix #2
  src/main/java/com/fsm/TransitionTable.java
Labels: enhancement

#41 Fix fsm
  src/main/java/com/core/Constants.java
  src/main/java/com/core/ParsedCommand.java
  src/main/java/com/core/RequestHandler.java
  src/main/java/com/fsm/FSM.java
  src/main/java/com/fsm/State.java
  src/main/java/com/fsm/States.java
  src/main/java/com/fsm/Transition.java
  src/main/java/com/fsm/TransitionTable.java
  src/test/java/com/core/FSMTest.java
  src/test/java/com/core/RequestHandlerTest.java
Labels: enhancement
